# Databricks Apps configuration
# Databricks automatically runs npm install and npm run build before starting
# This command only handles the server startup
command:
  - sh
  - -c
  - |
    uvicorn backend.main:app --host 0.0.0.0 --port 8000